services:
  - type: web
    name: ma9ic-romm
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "8080"
      - key: ROMM_AUTH_SECRET_KEY
        generateValue: true
      - key: DB_HOST
        value: "localhost"
      - key: HASHEOUS_API_ENABLED
        value: "true"
