services:
  - type: web
    name: ma9ic-drive-in
    runtime: docker
    plan: free
    dockerfilePath: ./kodi-web/Dockerfile
    dockerContext: ./kodi-web
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "10000"
